Gormv2: # 只针对 gorm  操作数据库有效
  Mysql:
    Host: "127.0.0.1"
    DataBase: "bubble"
    Port: 3306                        #注意，非3306，请自行调整
    User: "root"
    Pass: "123456"
    Charset: "utf8mb4"
    SetMaxIdleConns: 10
    SetMaxOpenConns: 128
    SetConnMaxLifetime: 60    # 连接不活动时的最大生存时间(秒)
    SlowThreshold: 30            # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
      #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
      #PingFailRetryTimes: 3   # 保留项,最大重连次数
